export const dataTableStyles = {
  wrapper: 'table-responsive saas-table-wrap',
  table: 'table ti-custom-table saas-data-table mb-0',
  thead: '',
  row: '',
  empty: 'saas-table-empty',
  emptyInner: 'flex flex-col items-center gap-1',
  emptyTitle: 'saas-table-empty-title mb-0',
  emptyDesc: 'text-textmuted text-sm mb-0',
  actions: 'saas-table-actions',
  checkbox: 'form-check-input',
  actionBase: 'ti-btn ti-btn-icon ti-btn-sm saas-action-btn',
  actionVariants: {
    view: 'ti-btn-success-light',
    edit: 'ti-btn-primary-light',
    delete: 'ti-btn-danger-light',
    default: 'ti-btn-primary-light',
  },
  thInner: 'saas-th-inner',
  sort: 'saas-sort',
  sortBtn: 'saas-sort-btn',
  footer: 'saas-table-footer',
  summary: 'text-xs text-textmuted mb-0',
  pagination: 'ti-pagination mb-0! ms-auto',
  pageItem: 'page-item',
  pageLink: 'page-link',
  pageLinkActive: 'page-link active',
  pageEllipsis: 'page-link pointer-events-none',
  bulkBar: 'flex flex-wrap items-center gap-2 px-3 py-1.5 border-b border-defaultborder bg-light/40',
  bulkSelect: 'form-control form-control-sm w-auto',
  selectCol: 'saas-col-select',
  actionsCol: 'saas-col-actions',
} as const
