export const dataTableStyles = {
  wrapper: 'table-responsive',
  table: 'table whitespace-nowrap ti-custom-table',
  thead: '',
  row: '',
  empty: 'text-center text-textmuted py-8',
  emptyInner: 'flex flex-col items-center gap-1 py-4',
  emptyTitle: 'font-medium text-defaulttextcolor mb-0',
  emptyDesc: 'text-textmuted text-sm mb-0',
  actions: 'hstack gap-2 fs-15',
  checkbox: 'form-check-input',
  actionBase: 'ti-btn ti-btn-icon waves-effect waves-light ti-btn-sm rounded-pill',
  actionVariants: {
    view: 'ti-btn-success-light',
    edit: 'ti-btn-primary-light',
    delete: 'ti-btn-danger-light',
    default: 'ti-btn-primary-light',
  },
  thInner: 'flex items-center gap-1',
  sort: 'inline-flex flex-col leading-none',
  sortBtn: 'ti-btn ti-btn-sm ti-btn-ghost-light !p-0 !min-w-0 !h-auto text-textmuted hover:text-primary',
  footer: 'flex gap-2 flex-wrap items-center border-t border-defaultborder px-4 py-3',
  summary: 'text-sm text-textmuted mb-0',
  pagination: 'ti-pagination mb-0! ms-auto',
  pageItem: 'page-item',
  pageLink: 'page-link',
  pageLinkActive: 'page-link active',
  pageEllipsis: 'page-link pointer-events-none',
  bulkBar: 'flex flex-wrap items-center gap-2 px-4 py-2 border-b border-defaultborder bg-light/40',
  bulkSelect: 'form-control form-control-sm w-auto',
} as const
